### PR TITLE
Update lots of stuff.

### PR DESCRIPTION
**Pull request by elliottneilclark**
Update ubuntu base version.
Update gcc.
Update clang.
Update boost.
Update folly.
Update wangle.

---
This change is [Reviewable](https://reviewable.io/reviews/philipjameson/cpp-docker/12)

### CODE REVIEW

**Comment by philipjameson** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[Dockerfile, line 6 \[r1\]](https://reviewable.io:443/reviews/philipjameson/cpp-docker/12#-KG6U-zGbs6yyt6w6iQY:-KG6U-zGbs6yyt6w6iQZ:1601702570) ([raw file](https://github.com/philipjameson/cpp-docker/blob/0d88a958bd483bb1f8fc92142b9c4959bf13c5a2/Dockerfile#L6)):*
Link to what this is about? I'm not familiar with it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/philipjameson/cpp-docker/12)*

**Comment by philipjameson** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/philipjameson/cpp-docker/12)*

**Comment by philipjameson** [comment]
This all seems pretty reasonable. I'll try building an image and pushing in the morning. I'm actually looking at moving some of this stuff over to chef shortly for building the image (it's almost done), so I might ask for a review when I do that.

**Comment by elliottneilclark** [comment]
Will do

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[Dockerfile, line 6 \[r1\]](https://reviewable.io:443/reviews/philipjameson/cpp-docker/12#-KG6U-zGbs6yyt6w6iQY:-KG8uY42GbX8YJ418lEs:-918571277) ([raw file](https://github.com/philipjameson/cpp-docker/blob/0d88a958bd483bb1f8fc92142b9c4959bf13c5a2/Dockerfile#L6)):*
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=68220

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/philipjameson/cpp-docker/12#-:-KG8uaMMw4ALopH8Y9ON:866299604)*

**Pull request merged**
