### PR TITLE
Moved dockerfile logic into cookbooks

### PR DESCRIPTION
**Pull request by philipjameson**
Moved the logic for building all of the libraries from the Dockerfile, into a set of cookbooks that can ideally be used later on to install natively on other platforms. Big thing here also is that everything is built into /opt/facebook, though that can be changed by setting the install_prefix in the attributes file

---
This change is [Reviewable](https://reviewable.io/reviews/philipjameson/cpp-docker/13)

### CODE REVIEW

**Comment by philipjameson** [comment]
@elliottneilclark @linuxfood

**Comment by philipjameson** [comment]
It does take a little longer to build now, since it checks out the boost git repo, rather than using a tarball from the fedora mirror. We can change that back if we have to

**Comment by elliottneilclark** [comment]
Pulling from git seems generally good. I'm not too worried about the slow down.

**Comment by philipjameson** [comment]
Yeah, it's only on build, so I wasn't super worried about it.

**Comment by philipjameson** [comment]
Also, this is built at pjameson/buck-folly-watchman:chef. I did move everything to /opt/facebook, so a couple of tweaks may be in order. I just had to change exported_preprocessor_flags to have -I/opt/facebook/include, then I changed my prebuilt_cxx_library rules to point to /opt/facebook/lib.

**Comment by elliottneilclark** [comment]
Review status: 0 of 31 files reviewed at latest revision, 4 unresolved discussions.

---

*[cookbooks/fbcode/recipes/boost.rb, line 12 \[r1\]](https://reviewable.io:443/reviews/philipjameson/cpp-docker/13#-KGmS4giqdNRhJyva1Hm:-KGmS4giqdNRhJyva1Hn:975826109) ([raw file](https://github.com/philipjameson/cpp-docker/blob/2866364b9363357a78f38a8a015fee74a9d23148/cookbooks/fbcode/recipes/boost.rb#L12)):*
Why just atomic?

---

*[cookbooks/fbcode/recipes/build_gcc.rb, line 32 \[r1\]](https://reviewable.io:443/reviews/philipjameson/cpp-docker/13#-KGmSjQNNU4FcjCv7qgi:-KGmSjQNNU4FcjCv7qgj:-1023377468) ([raw file](https://github.com/philipjameson/cpp-docker/blob/2866364b9363357a78f38a8a015fee74a9d23148/cookbooks/fbcode/recipes/build_gcc.rb#L32)):*
Should this include fbcode?

---

*[cookbooks/fbcode/recipes/build_gcc.rb, line 42 \[r1\]](https://reviewable.io:443/reviews/philipjameson/cpp-docker/13#-KGmTrPTC1r__t2t1zvB:-KGmTrPTC1r__t2t1zvC:1573318089) ([raw file](https://github.com/philipjameson/cpp-docker/blob/2866364b9363357a78f38a8a015fee74a9d23148/cookbooks/fbcode/recipes/build_gcc.rb#L42)):*
Why not gcc4-compatible ?

---

*[cookbooks/fbcode/recipes/clang.rb, line 3 \[r1\]](https://reviewable.io:443/reviews/philipjameson/cpp-docker/13#-KGmUATjP4hTmmiZDuCN:-KGmUATkGPRlsLY76Rd4:-931290424) ([raw file](https://github.com/philipjameson/cpp-docker/blob/2866364b9363357a78f38a8a015fee74a9d23148/cookbooks/fbcode/recipes/clang.rb#L3)):*
Should we compile this from git like gcc?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/philipjameson/cpp-docker/13)*

**Comment by philipjameson** [comment]
Review status: 0 of 31 files reviewed at latest revision, 4 unresolved discussions.

---

*[cookbooks/fbcode/recipes/boost.rb, line 12 \[r1\]](https://reviewable.io:443/reviews/philipjameson/cpp-docker/13#-KGmS4giqdNRhJyva1Hm:-KGmUrq9_itrg2H18743:-337596854) ([raw file](https://github.com/philipjameson/cpp-docker/blob/2866364b9363357a78f38a8a015fee74a9d23148/cookbooks/fbcode/recipes/boost.rb#L12)):*
The output_file property is used to determine whether we should rebuild if the git repo doesn't change. I was just grabbing a single file that boost uses to signal that it's been built. The library was arbitrary.

---

*[cookbooks/fbcode/recipes/build_gcc.rb, line 32 \[r1\]](https://reviewable.io:443/reviews/philipjameson/cpp-docker/13#-KGmSjQNNU4FcjCv7qgi:-KGmV7kTITcq0hbQOd6D:1470435347) ([raw file](https://github.com/philipjameson/cpp-docker/blob/2866364b9363357a78f38a8a015fee74a9d23148/cookbooks/fbcode/recipes/build_gcc.rb#L32)):*
I guess maybe it should. Right now, the build gcc stuff works, but I don't use it anywhere, so it's probably not a huge deal.

---

*[cookbooks/fbcode/recipes/build_gcc.rb, line 42 \[r1\]](https://reviewable.io:443/reviews/philipjameson/cpp-docker/13#-KGmTrPTC1r__t2t1zvB:-KGmVJoYpSLYteZgnDi0:1300609720) ([raw file](https://github.com/philipjameson/cpp-docker/blob/2866364b9363357a78f38a8a015fee74a9d23148/cookbooks/fbcode/recipes/build_gcc.rb#L42)):*
I was just ripping the build flags from the current system gcc in 16.04, so I hadn't looked at it super closely. If the system is built with the new abi, though, is there a reason not to use it?

---

*[cookbooks/fbcode/recipes/clang.rb, line 3 \[r1\]](https://reviewable.io:443/reviews/philipjameson/cpp-docker/13#-KGmUATjP4hTmmiZDuCN:-KGmVYuiZ6xtvP3aZs6j:-1428495628) ([raw file](https://github.com/philipjameson/cpp-docker/blob/2866364b9363357a78f38a8a015fee74a9d23148/cookbooks/fbcode/recipes/clang.rb#L3)):*
I only did it with gcc because there were no readily available 5.3 dpkgs available at the time. Clang are awesome and just ship packages, which are good enough, I think.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/philipjameson/cpp-docker/13)*

**Comment by elliottneilclark** [comment]
Review status: 0 of 31 files reviewed at latest revision, 3 unresolved discussions.

---

*[cookbooks/fbcode/recipes/boost.rb, line 12 \[r1\]](https://reviewable.io:443/reviews/philipjameson/cpp-docker/13#-KGmS4giqdNRhJyva1Hm:-KGmqA4avf2eJhi3nxCY:-1056755125) ([raw file](https://github.com/philipjameson/cpp-docker/blob/2866364b9363357a78f38a8a015fee74a9d23148/cookbooks/fbcode/recipes/boost.rb#L12)):*
Probably not a big deal. But we have to hope that the build doesn't error out part way through.

---

*[cookbooks/fbcode/recipes/build_gcc.rb, line 42 \[r1\]](https://reviewable.io:443/reviews/philipjameson/cpp-docker/13#-KGmTrPTC1r__t2t1zvB:-KGmqNSCcbPO-eAv1IbI:-609715828) ([raw file](https://github.com/philipjameson/cpp-docker/blob/2866364b9363357a78f38a8a015fee74a9d23148/cookbooks/fbcode/recipes/build_gcc.rb#L42)):*
Yeah the gcc devs are jerks. They added a new ABI that's not backwards compatible. So if you want to build with gcc5+ and run against older libstdc++ or with clang you have to turn the new abi off. Since that's done for all of the things buck builds with -D_GLIBCXX_USE_CXX11_ABI=0 it might be easier to just do it here.

Then we can remove that from the cxxflags.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/philipjameson/cpp-docker/13)*

**Comment by andrewchalfant** [comment]
Reviewed 31 of 31 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/philipjameson/cpp-docker/13)*

**Comment by philipjameson** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[cookbooks/fbcode/recipes/boost.rb, line 12 \[r1\]](https://reviewable.io:443/reviews/philipjameson/cpp-docker/13#-KGmS4giqdNRhJyva1Hm:-KGnC74Ev5eRuB3j50Rs:1666354738) ([raw file](https://github.com/philipjameson/cpp-docker/blob/2866364b9363357a78f38a8a015fee74a9d23148/cookbooks/fbcode/recipes/boost.rb#L12)):*
Yeah, though if it makes it though make, and then fails part way through make install.... :/ This was a quick and dirty way to do it. If you have another suggestion, I'm all ears. I just didn't want us constantly rebuilding things that didn't need rebuilt.

---

*[cookbooks/fbcode/recipes/build_gcc.rb, line 42 \[r1\]](https://reviewable.io:443/reviews/philipjameson/cpp-docker/13#-KGmTrPTC1r__t2t1zvB:-KGnCK8Az0S4MG6I5eni:-1478969893) ([raw file](https://github.com/philipjameson/cpp-docker/blob/2866364b9363357a78f38a8a015fee74a9d23148/cookbooks/fbcode/recipes/build_gcc.rb#L42)):*
I'll have to dig in to see what the newer versions of ubuntu use. I would have guessed that if they used the new ABI in their compiler, that they used it in their libs, otherwise it would be a pain to use. Maybe it's best to make this configurable?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/philipjameson/cpp-docker/13)*

**Comment by elliottneilclark** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[cookbooks/fbcode/recipes/build_gcc.rb, line 42 \[r1\]](https://reviewable.io:443/reviews/philipjameson/cpp-docker/13#-KGmTrPTC1r__t2t1zvB:-KH687IDiFaE27eqif2o:1357722891) ([raw file](https://github.com/philipjameson/cpp-docker/blob/2866364b9363357a78f38a8a015fee74a9d23148/cookbooks/fbcode/recipes/build_gcc.rb#L42)):*
So actually I take it back we should leave it on since that leaves it up to the users. They can either have the clfags turn it off or not. Giving them the option seems better.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/philipjameson/cpp-docker/13)*

**Comment by elliottneilclark** [comment]
lgtm

**Pull request merged**
